# Generated by Django 3.2.8 on 2021-10-21 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoYourChores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('day', models.CharField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], max_length=1)),
            ],
        ),
    ]
