# Generated by Django 3.2.8 on 2021-10-21 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoYourChores', '0002_chores'),
    ]

    operations = [
        migrations.RenameField(
            model_name='housemate',
            old_name='phoneNumber',
            new_name='phone_number',
        ),
    ]
