# Generated by Django 3.2.8 on 2021-10-21 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DoYourChores', '0003_rename_phonenumber_housemate_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='housemate',
            name='available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housemate',
            name='current_chore_handler',
            field=models.BooleanField(default=False),
        ),
    ]
