# Generated by Django 3.2.8 on 2021-10-21 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DoYourChores', '0004_auto_20211021_0201'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Chores',
            new_name='Chore',
        ),
    ]
